name: Deploy Minecraft Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "🚀 Начинаем деплой..."
            cd /root/minecraft-bot
            git reset --hard HEAD
            echo "📁 Забираем последние изменения"
            git pull origin main
            
            echo "🔄 Перезапускаем сервис..."
            if systemctl restart minecraft-bot.service; then
              echo "✅ Сервис успешно перезапущен"
              systemctl status minecraft-bot.service --no-pager
            else
              echo "❌ Ошибка при перезапуске сервиса"
              echo "⚠️ Проверьте: sudo systemctl status minecraft-bot.service"
            fi
            echo "✅ Деплой завершен!!!"